name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'enhancement'
  - title: '🏎️ Performance'
    labels:
      - 'performance'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🔨 Refactor'
    labels:
      - 'refactor'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
  - title: '🧰 Maintenance'
    labels:
      - 'dependencies'
      - 'maintenance'
      - 'ci'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
autolabeler:
  - label: 'fix'
    branch:
      - '/fix\/.+/'
  - label: 'enhancement'
    branch:
      - '/feat\/.+/'
  - label: 'performance'
    branch:
      - '/perf\/.+/'
  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
  - label: 'documentation'
    branch:
      - '/docs\/.+/'
  - label: 'maintenance'
    branch:
      - '/chore\/.+/'
      - '/ci\/.+/'
      - '/deps\/.+/'

template: |
  ## Changelog 📝

  $CHANGES
