# Production
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

  server:
    image: ghcr.io/jayllyz/cinema-api:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data:
    driver: local
